### PR TITLE
Fixed bugs in export events, added support for environment variables, and added code coverage

### PR DESCRIPTION
**Pull request by annietjx**

### CODE REVIEW

**Review by Phantom65536 — APPROVED** [review]
Great you wrote Javadoc and addressed the issues I mentioned in my last code review. CA and SOLID principles are still adhered. Appreciate it.

**Review by Benallegue-Mehdi — CHANGES_REQUESTED** [review]
Great application of SOLID principles through the use of documentation and the factory design pattern! However, please make sure to remove the test coverage files before merging this. Thank you!

**Comment by annietjx** [comment]
@Benallegue-Mehdi Could I know why I need to remove the test coverage files?

**Comment by Benallegue-Mehdi** [comment]
@annietjx The text coverage files are ~ 45-46k lines long, which would highly skew the Contributors graph. I think it would be preferable to not push the test coverage files, as doing so would require you to justify why your line count is so high when submitting your individual contribution.

**Comment by annietjx** [comment]
Please refer to the latest commit. Thanks

**Review by Benallegue-Mehdi — APPROVED** [review]
I approve this PR now that the test coverage has been removed.

**Pull request merged**
